### ISSUE TITLE
issue with lightning pose installation

### ISSUE THREAD

**Issue by Chrysovalantis000** [danbider/lightning-pose#152]
lightning pose prompted to install an update
went through ok - no issue

used LP for a while - firefox then prompted for update
updated firefox
now when calling: "lightning run app app.py" nothing happens and we get: "Please call `fabric run model` instead"
when running this we now get

$ fabric run model /home/lightning-pose/Pose-app/app.py
Traceback (most recent call last):
  File "/home/lightning-pose/Pose-app/app.py", line 336, in <module>
    app = LightningApp(LitPoseApp())
  File "/home/lightning-pose/Pose-app/app.py", line 59, in __init__
    default_config_dict = yaml.safe_load(open(os.path.join(config_dir, "config_default.yaml")))
FileNotFoundError: [Errno 2] No such file or directory: 'lightning-pose/scripts/configs/config_default.yaml'
[2024-04-23 13:04:26,639] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 6409) of binary: /home/lightning-pose/anaconda3/envs/lai/bin/python
Traceback (most recent call last):
  File "/home/lightning-pose/anaconda3/envs/lai/bin/fabric", line 8, in <module>
    sys.exit(_main())
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/lightning/fabric/cli.py", line 159, in _run_model
    main(args=Namespace(**kwargs), script_args=script_args)
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/lightning/fabric/cli.py", line 217, in main
    _torchrun_launch(args, script_args or [])
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/lightning/fabric/cli.py", line 212, in _torchrun_launch
    torchrun.main(torchrun_args)
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lightning-pose/anaconda3/envs/lai/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/lightning-pose/Pose-app/app.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-23_13:04:26
  host      : lightningpose-901045
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 6409)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
  
  
  
  bit unsure how to fix our current system now...
  
do we need to convert our system/code to fabric? https://lightning.ai/docs/fabric/stable/fundamentals/convert.html

bit unsure!

log files - where are they (path) for analysis later?

any pointers or more recent documentation would be gratefully received....

*****A short question about the online version: how does the GPU is used? I created an account yesterday and I used it for few minutes, I left it open and today I needed to pay. So how should i save GPU hours?
Anyway I think the online version is problematic in terms of GPU hours allowance so i would like to install it locally. Could you please help with the above situation?

Have a good day!

**Comment by themattinthehatt** [comment]
Hi @Chrysovalantis000, thanks for getting in touch. 

Regarding your first question, there are actually 3 different packages at play: lightning, which is a generic framework for training and the app, not developed by us; lightning-pose, which we develop on top of lightning; and Pose-app, which we also develop on top of lightning.

The update prompt that you saw was actually for lightning, and for now we ask that you **don't** answer yes; we say that in the docs [here](https://pose-app.readthedocs.io/en/latest/source/using_the_app.html) but obviously it's a bit buried. If you have suggestions for how to make this clearer to a user please let us know!

You can revert to the old version of lightning by running
```
pip install lightning==2.1.3
```
You might get some error message saying it's incompatible with other package versions but it should be ok. Please let me know how this works.

For the online version, once you are connected to a GPU machine you are paying for that GPU machine, regardless of whether or not the GPU is in use. If you leave the app running then the Studio will stay open and continue to charge you for use of the GPU machine. If you are not doing anything in the studio (no training or inference, not running the app, etc.) then the Studio should shut itself down after 10 minutes of inactivity.

Steps for local installation can be found [here](https://pose-app.readthedocs.io/en/latest/source/getting_started.html#install-app-from-github), let me know if anything isn't clear!

**Comment by themattinthehatt** [comment]
@Chrysovalantis000 just wanted to check in on this, were you able to get everything up and running ok?

**Comment by themattinthehatt** [comment]
closing due to inactivity
